Unprotected code cause SimpleStatistic to crash
I've updated the dist file in order to work for me, you should think about SRC.
Cordialy.

/Users/lreenaers/Documents/code/IFly/node_modules/simple-statistics/dist/simple-statistics.js:1641
        throw new Error("sampleVariance requires at least two data points");
              ^

Error: sampleVariance requires at least two data points
    at Object.sampleVariance (/Users/lreenaers/Documents/code/IFly/node_modules/simple-statistics/dist/simple-statistics.js:1641:15)
    at IGCAnalyzer.parse (/Users/lreenaers/Documents/code/IFly/node_modules/igc-analyzer/dist/igc-analyzer.js:519:48)
    at /Users/lreenaers/Documents/code/IFly/index.js:106:35
    at Array.forEach (<anonymous>)
    at processFlights (/Users/lreenaers/Documents/code/IFly/index.js:85:8)
    at Statement.<anonymous> (/Users/lreenaers/Documents/code/IFly/index.js:188:5)
    at Statement.replacement (/Users/lreenaers/Documents/code/IFly/node_modules/sqlite3/lib/trace.js:25:27)